server:
  port: 8083
spring:
  application:
    name: eureka-client-user-service
eureka:
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://admin:123123@localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5